
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CodigoPanel = new javax.swing.JScrollPane();
        CodgioArea = new javax.swing.JTextArea();
        CompilarLbl = new javax.swing.JLabel();
        SegundoPanel = new javax.swing.JTabbedPane();
        LexicoPanel = new javax.swing.JScrollPane();
        LexicoArea = new javax.swing.JTextArea();
        SintacticoPanel = new javax.swing.JScrollPane();
        SintacticoArea = new javax.swing.JTextArea();
        SemanticoPanel = new javax.swing.JScrollPane();
        SemanticoArea = new javax.swing.JTextArea();
        IntermedioPanel = new javax.swing.JScrollPane();
        IntermedioArea = new javax.swing.JTextArea();
        PanelAbajo = new javax.swing.JTabbedPane();
        ErrorPanel = new javax.swing.JScrollPane();
        ErrorArea = new javax.swing.JTextArea();
        ResultadosPanel = new javax.swing.JScrollPane();
        ResultadosArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArchivoBtn = new javax.swing.JMenu();
        NuevoBtn = new javax.swing.JMenuItem();
        AbrirBtn = new javax.swing.JMenuItem();
        GuardarBtn = new javax.swing.JMenuItem();
        EditarBtn = new javax.swing.JMenu();
        FormatoBtn = new javax.swing.JMenu();
        CompilarBtn = new javax.swing.JMenu();
        AyudaBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JACHI");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setAutoscrolls(true);

        CodigoPanel.setBackground(new java.awt.Color(102, 102, 102));

        CodgioArea.setBackground(new java.awt.Color(102, 102, 102));
        CodgioArea.setColumns(20);
        CodgioArea.setForeground(new java.awt.Color(255, 153, 153));
        CodgioArea.setRows(5);
        CodgioArea.setAutoscrolls(false);
        CodigoPanel.setViewportView(CodgioArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CodigoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(CodigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CompilarLbl.setText("Codigo a compilar");

        SegundoPanel.setBackground(new java.awt.Color(102, 102, 102));
        SegundoPanel.setForeground(new java.awt.Color(102, 102, 102));

        LexicoPanel.setBackground(new java.awt.Color(0, 0, 0));
        LexicoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LexicoArea.setBackground(new java.awt.Color(102, 102, 102));
        LexicoArea.setColumns(20);
        LexicoArea.setForeground(new java.awt.Color(255, 153, 153));
        LexicoArea.setLineWrap(true);
        LexicoArea.setRows(5);
        LexicoArea.setText("Lexico");
        LexicoPanel.setViewportView(LexicoArea);

        SegundoPanel.addTab("Lexico", LexicoPanel);

        SintacticoArea.setBackground(new java.awt.Color(102, 102, 102));
        SintacticoArea.setColumns(20);
        SintacticoArea.setForeground(new java.awt.Color(255, 153, 153));
        SintacticoArea.setRows(5);
        SintacticoArea.setText("Sintactico\n");
        SintacticoPanel.setViewportView(SintacticoArea);

        SegundoPanel.addTab("Sintanctico", SintacticoPanel);

        SemanticoArea.setBackground(new java.awt.Color(102, 102, 102));
        SemanticoArea.setColumns(20);
        SemanticoArea.setForeground(new java.awt.Color(255, 153, 153));
        SemanticoArea.setRows(5);
        SemanticoArea.setText("Semantico\n");
        SemanticoPanel.setViewportView(SemanticoArea);

        SegundoPanel.addTab("Semantico", SemanticoPanel);

        IntermedioArea.setBackground(new java.awt.Color(102, 102, 102));
        IntermedioArea.setColumns(20);
        IntermedioArea.setForeground(new java.awt.Color(255, 153, 153));
        IntermedioArea.setRows(5);
        IntermedioPanel.setViewportView(IntermedioArea);

        SegundoPanel.addTab("Codigo intermedio", IntermedioPanel);

        PanelAbajo.setBackground(new java.awt.Color(102, 102, 102));

        ErrorPanel.setBackground(new java.awt.Color(102, 102, 102));

        ErrorArea.setBackground(new java.awt.Color(102, 102, 102));
        ErrorArea.setColumns(20);
        ErrorArea.setForeground(new java.awt.Color(255, 153, 153));
        ErrorArea.setRows(5);
        ErrorArea.setText("Error");
        ErrorPanel.setViewportView(ErrorArea);

        PanelAbajo.addTab("Errores", ErrorPanel);

        ResultadosPanel.setBackground(new java.awt.Color(102, 102, 102));

        ResultadosArea.setBackground(new java.awt.Color(102, 102, 102));
        ResultadosArea.setColumns(20);
        ResultadosArea.setForeground(new java.awt.Color(255, 153, 153));
        ResultadosArea.setRows(5);
        ResultadosArea.setText("Resultados");
        ResultadosPanel.setViewportView(ResultadosArea);

        PanelAbajo.addTab("Resultados", ResultadosPanel);

        ArchivoBtn.setText("Archivo");

        NuevoBtn.setText("Nuevo");
        NuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoBtnActionPerformed(evt);
            }
        });
        ArchivoBtn.add(NuevoBtn);

        AbrirBtn.setText("Abrir");
        AbrirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBtnActionPerformed(evt);
            }
        });
        ArchivoBtn.add(AbrirBtn);

        GuardarBtn.setText("Guardar");
        GuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtnActionPerformed(evt);
            }
        });
        ArchivoBtn.add(GuardarBtn);

        jMenuBar1.add(ArchivoBtn);

        EditarBtn.setText("Editar");
        jMenuBar1.add(EditarBtn);

        FormatoBtn.setText("Formato");
        jMenuBar1.add(FormatoBtn);

        CompilarBtn.setText("Compilar");
        jMenuBar1.add(CompilarBtn);

        AyudaBtn.setText("Ayuda");
        jMenuBar1.add(AyudaBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompilarLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAbajo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(CompilarLbl)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SegundoPanel)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String path;
    private void AbrirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        String codigo = new String();
        path = fileChooser.getSelectedFile().getAbsolutePath();
        File archivo = new File(path);
        FileReader fr = null;
        BufferedReader entrada = null;
        try {
            fr = new FileReader(path);
            entrada = new BufferedReader(fr);
            while(entrada.ready()){
                codigo += entrada.readLine();
                codigo += "\n";
                //this.CodgioArea.setText(entrada.readLine());
                //System.out.println(entrada.readLine());
            }
            this.CodgioArea.setText(codigo);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AbrirBtnActionPerformed

    private void GuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtnActionPerformed
        // TODO add your handling code here:
        FileWriter fw;
       // String ruta = "C:\\Users\\Carlos\\Documents\\Octavo semestre\\Compiladores\\IDE de compiladores\\prueba.txt";
        try {
            //Se abre el archivo para escribir
            fw= new FileWriter(path);
            //se escribe el nuevo codigo en el archivo
            fw.write(this.CodgioArea.getText());
            //se cierra el archivo
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_GuardarBtnActionPerformed

    private void NuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        String codigo = new String();
        path = fileChooser.getSelectedFile().getAbsolutePath();
        File archivo = new File(path);
        FileReader fr = null;
        if(!archivo.exists()){
            try {
                archivo.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         FileWriter fw;
        try {
            fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("");
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.CodgioArea.setText("");
         
    }//GEN-LAST:event_NuevoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirBtn;
    private javax.swing.JMenu ArchivoBtn;
    private javax.swing.JMenu AyudaBtn;
    private javax.swing.JTextArea CodgioArea;
    private javax.swing.JScrollPane CodigoPanel;
    private javax.swing.JMenu CompilarBtn;
    private javax.swing.JLabel CompilarLbl;
    private javax.swing.JMenu EditarBtn;
    private javax.swing.JTextArea ErrorArea;
    private javax.swing.JScrollPane ErrorPanel;
    private javax.swing.JMenu FormatoBtn;
    private javax.swing.JMenuItem GuardarBtn;
    private javax.swing.JTextArea IntermedioArea;
    private javax.swing.JScrollPane IntermedioPanel;
    private javax.swing.JTextArea LexicoArea;
    private javax.swing.JScrollPane LexicoPanel;
    private javax.swing.JMenuItem NuevoBtn;
    private javax.swing.JTabbedPane PanelAbajo;
    private javax.swing.JTextArea ResultadosArea;
    private javax.swing.JScrollPane ResultadosPanel;
    private javax.swing.JTabbedPane SegundoPanel;
    private javax.swing.JTextArea SemanticoArea;
    private javax.swing.JScrollPane SemanticoPanel;
    private javax.swing.JTextArea SintacticoArea;
    private javax.swing.JScrollPane SintacticoPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
